# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]	
	
#7 segment display
set_property PACKAGE_PIN W7 [get_ports {display[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[0]}]
set_property PACKAGE_PIN W6 [get_ports {display[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[1]}]
set_property PACKAGE_PIN U8 [get_ports {display[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[2]}]
set_property PACKAGE_PIN V8 [get_ports {display[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[3]}]
set_property PACKAGE_PIN U5 [get_ports {display[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[4]}]
set_property PACKAGE_PIN V5 [get_ports {display[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[5]}]
set_property PACKAGE_PIN U7 [get_ports {display[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[6]}]

#set_property PACKAGE_PIN V7 [get_ports dp]							
	#set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {digit[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[0]}]
set_property PACKAGE_PIN U4 [get_ports {digit[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[1]}]
set_property PACKAGE_PIN V4 [get_ports {digit[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[2]}]
set_property PACKAGE_PIN W4 [get_ports {digit[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[3]}]


#Buttons
set_property PACKAGE_PIN U18 [get_ports rst]						
	set_property IOSTANDARD LVCMOS33 [get_ports rst]				

# Switches
 set_property PACKAGE_PIN V17 [get_ports {sw[0]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
 set_property PACKAGE_PIN V16 [get_ports {sw[1]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
 set_property PACKAGE_PIN W16 [get_ports {sw[2]}]
 set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
# set_property PACKAGE_PIN W17 [get_ports {switch[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
# set_property PACKAGE_PIN W15 [get_ports {switch[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
# set_property PACKAGE_PIN V15 [get_ports {switch[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {switch[5]}]
# set_property PACKAGE_PIN W14 [get_ports {switch[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {switch[6]}]
# set_property PACKAGE_PIN W13 [get_ports {switch[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {switch[7]}]
# set_property PACKAGE_PIN V2 [get_ports {switch[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {switch[8]}]
# set_property PACKAGE_PIN T3 [get_ports {switch[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {switch[9]}]
# set_property PACKAGE_PIN T2 [get_ports {switch[10]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {switch[10]}]
# set_property PACKAGE_PIN R3 [get_ports {switch[11]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {switch[11]}]
# set_property PACKAGE_PIN W2 [get_ports {switch[12]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {switch[12]}]
# set_property PACKAGE_PIN U1 [get_ports {switch[13]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {switch[13]}]
 set_property PACKAGE_PIN T1 [get_ports {sw15}]
 set_property IOSTANDARD LVCMOS33 [get_ports {sw15}]
 set_property PACKAGE_PIN R2 [get_ports {sw16}]
 set_property IOSTANDARD LVCMOS33 [get_ports {sw16}]
 
#USB HID (PS/2)
set_property PACKAGE_PIN C17 [get_ports PS2_CLK]						
	set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
	set_property PULLUP true [get_ports PS2_CLK]
set_property PACKAGE_PIN B17 [get_ports PS2_DATA]					
	set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]	
	set_property PULLUP true [get_ports PS2_DATA]

